version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: ./docker_images/production/app/Dockerfile
    volumes:
      - .:/app

  nginx:
    build: ./docker_images/production/nginx/
    ports:
      - "80:80"
    volumes:
      - .:/app
    depends_on:
      - "app"