version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: ./docker_images/production/app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  nginx:
    build: ./docker_images/production/nginx/
    ports:
      - "80:80"